export const projects = [
  {
    id: 1,
    title: "Project Name",
    description: "Project description",
    technologies: ["React", "Next.js"],
    image: "/images/project1.jpg",
    github: "https://github.com/...",
    demo: "https://demo.com",
  },
];

export const skills = [
  "JavaScript",
  "React",
  "Next.js",
  "TypeScript",
  "Swift",
  "Kotlin",
  "Java",
  "CSS",
  "HTML",
  "Node.js",
  "Express",
  "MongoDB",
  "Git",
  "Docker",
  "Figma",
  "Photoshop",
  "Illustrator",
  "After Effects",
  "Premiere Pro",
  "WordPress",
  "Shopify",
  "SEO",
  "Content Creation",
  "UI/UX Design",
  "Agile Methodologies",
  "Project Management",
  "Communication",
  "Problem-Solving",
  "Team Collaboration",
  "Time Management",
  "Adaptability",
  "Critical Thinking",
];
