import { m } from "framer-motion";
import { ca } from "zod/v4/locales";

export const languages = [
  "JavaScript",
  "TypeScript",
  "Swift",
  "Kotlin",
  "Java",
  "CSS",
  "HTML",
  "SQL",
  "NoSQL",
  "Python",
  "C#",
  "C++",
];
export const frameworks = [
  "Node.js",
  "Next.js",
  "Vue.js",
  "Vuetify",
  "ASP.NET",
  "Express.js",
];

export const IDEs = [
  "Visual Studio Code",
  "Visual Studio",
  "Unity",
  "HeidiSQL",
  "PhpStorm",
  "Eclipse",
  "Android Studio",
  "Xcode",
  "IntelliJ IDEA",
];
export const skils=[
  {name: "JavaScript", category: "language", mastery: "4/5"}, 
  {name: "TypeScript", category: "language", mastery: "4/5"},
  {name: "Swift", category: "language", mastery: "4/5"}, ,
  {name: "Kotlin", category: "language", mastery: "3/5"},
  {name: "Java", category: "language", mastery: "3/5"},
  {name: "CSS", category: "language", mastery: "4/5"},
  {name: "HTML", category: "language", mastery: "4/5"},
  {name: "SQL", category: "language", mastery: "3/5"},
  {name: "NoSQL", category: "language"},    
  {name: "Python", category: "language"},
  {name: "C#", category: "language"},
  {name: "C++", category: "language"},
  {name: "Node.js", category: "framework"},
  {name: "Next.js", category: "framework"},
  {name: "Vue.js", category: "framework"},
  {name: "Vuetify",  category: "framework"},
  {name: "ASP.NET", category: "framework"},
  {name: "Express.js", category: "framework"},
  {name: "Visual Studio Code", category: "IDE"},
  {name: "Visual Studio", category: "IDE"},
  {name: "Unity", category: "IDE"},
  {name: "HeidiSQL", category: "IDE"},
  {name: "PhpStorm", category: "IDE"},
  {name: "Eclipse",   category: "IDE"},
  {name: "Android Studio", category: "IDE"},
  {name: "Xcode",   category: "IDE"},
  {name: "IntelliJ IDEA", category: "IDE"},
  {name: "Git", category: "tool"},
  {name: "GitHub", category: "tool"},
  {name: "Jira", category: "tool"},
  {name: "Figma", category: "tool"},
  {name: "Adobe XD", category: "tool"},
  {name: "Photoshop", category: "tool"},
  {name: "Illustrator", category: "tool"},
  {name: "Pycharm", category: "IDE"},
  {name: "Agile Methodologies", category: "methodology"},
  {name: "Scrum", category: "methodology"},
  {name: "Test-Driven Development (TDD)", category: "methodology"},
  {name: "Behavior-Driven Development (BDD)", category: "methodology"},
  {name: "Continuous Integration/Continuous Deployment (CI/CD)", category: "methodology"},
  {name: "RESTful APIs", category: "methodology"},
  {name: "Microservices Architecture", category: "methodology"},
  {name: "Responsive Web Design", category: "methodology"},
  {name: "Progressive Web Apps (PWA)", category: "methodology"},
  {name: "Cross-Browser Compatibility", category: "methodology"},
  {name: "Performance Optimization", category: "methodology"},
  {name: "Security Best Practices", category: "methodology"},
  {name: "Accessibility Standards", category: "methodology"},
]
